### ISSUE TITLE
Restart and restart from checkpoint 

### ISSUE THREAD

**Issue by NfuDev** [Arrowsdev/Arrows_Missions_System_Plugin#4]
the logics for this feature is not finished , we have the types and properties set , i'll implement it in the next couple of days

**Comment by NfuDev** [comment]
a bit confused about restarting in case of multiple quests are running, but maybe also am wrong and even rpg games runs one quest at a time , this is open for discussion

**Comment by ahmedamirabbas** [comment]
> a bit confused about restarting in case of multiple quests are running, but maybe also am wrong and even rpg games runs one quest at a time , this is open for discussion 

I believe running multiple quests is a feature in most RPGs

**Comment by NfuDev** [comment]
i implemented some logics for it still didnt test them yet, but did some quick value check and everything seems to work fine

when restarting a mission or a quest we choose if from check point or beginning, so when that heppens we remove the current instance of the mission directly from the missions list without marking canceled as we did with the cancel logics and we keep other active missions alive and only start the selected mission, this is cool right now but i bet it will have some issues when it comes to missions that relocate the player in certain places like in gta when the take you to another city for just one mission
